### ISSUE TITLE
Not compatible with Espo 8.0.1

### ISSUE THREAD

**Issue by ChrisSka** [telecastg/dynamic-checklist-for-espocrm#3]
After update the detail view is no longer loaded.
The following error message appears in the console:

Uncaught (in promise) TypeError: this.escapeValue is not a function

    at o.getItemHtml (dynamic-checklist.js?r=1694943248:78:35)
    at eval (dynamic-checklist.js?r=1694943248:49:40)
    at Array.forEach (<anonymous>)
    at o.data (dynamic-checklist.js?r=1694943248:48:35)
    at o._getData (bullbone.umd.js:1574:29)
    at bullbone.umd.js:1659:37
    at s (bullbone.umd.js:1613:21)
    at o._getNestedViewsHtmlMap (bullbone.umd.js:1617:13)
    at o._getHtml (bullbone.umd.js:1658:18)
    at o.getHtml (bullbone.umd.js:1183:18)

**Comment by ChrisSka** [comment]
Works again. Thanks
